from pathlib import Path
BASE_PATH = Path().absolute()


STORIES_SERVICE_IP = '172.20.0.1'
STORIES_SERVICE_PORT = '5001'

USERS_SERVICE_IP = '172.20.0.1'
USERS_SERVICE_PORT = '5002'

DICE_SERVICE_IP = '172.20.0.1'
DICE_SERVICE_PORT = '5003'

PROFILING_SERVICE_IP = '172.20.0.1'
PROFILING_SERVICE_PORT = '5004'

REACTIONS_SERVICE_IP = '172.20.0.1'
REACTIONS_SERVICE_PORT = '5005'

LOGIN_URL = "http://{}:{}/login".format(USERS_SERVICE_IP, USERS_SERVICE_PORT)
SIGNUP_URL = "http://{}:{}/signup".format(USERS_SERVICE_IP, USERS_SERVICE_PORT)
GET_USER_URL = "http://{}:{}/user".format(USERS_SERVICE_IP, USERS_SERVICE_PORT) # add user is end of the string by using format